# Generated by Django 6.1.1 on 2026-09-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='furniture/', verbose_name='Изображение предмета')),
            ],
            options={
                'verbose_name': 'Предмет мебели',
                'verbose_name_plural': 'Каталог мебели',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя комната', max_length=50, verbose_name='Комната')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField(default=0, verbose_name='Координата X (px)')),
                ('y_pos', models.IntegerField(default=0, verbose_name='Координата Y (px)')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.furniture', verbose_name='Предмет мебели')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_furniture', to='constructor.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Размещенный предмет',
                'verbose_name_plural': 'Размещенная мебель в комнатах',
            },
        ),
    ]
