# Generated by Django 6.1.1 on 2026-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomfurniture',
            name='height',
            field=models.IntegerField(default=80, verbose_name='Высота (px)'),
        ),
        migrations.AddField(
            model_name='roomfurniture',
            name='rotation',
            field=models.IntegerField(default=0, verbose_name='Угол поворота (гр.)'),
        ),
        migrations.AddField(
            model_name='roomfurniture',
            name='width',
            field=models.IntegerField(default=80, verbose_name='Ширина (px)'),
        ),
    ]
